SDK-38 Fix incorrect timestamp units in documentation
Infinario/android-sdk pull request #2
Opened 2017-01-03 12:32 UTC by petee-d

Documentation said seconds, code sample suggested microseconds, code
actually expects milliseconds. Fixed all to milliseconds to maintain
backwards compatibility even though Exponea clients usually use seconds.

2017-01-03 12:48 UTC, ms7s requested changes
This may be clarified a bit more

2017-01-03 12:48 UTC, ms7s commented on src/main/java/com/infinario/android/infinariosdk/Infinario.java
> +     * @param timestamp  event's timestamp in milliseconds
This could specify epoch as well: `milliseconds since 1970-01-01 00:00:00 GMT`

2017-01-03 12:48 UTC, ms7s commented on README.md
> +Next two arguments are <code>Map&lt;String, Object&gt; properties</code> and <code>Long timestamp</code>. Properties is a map which uses <code>String</code> keys and the value may be any <code>Object
I would replace `standard UNIX timestamp in milliseconds` with `timestamp in milliseconds since 1970-01-01 00:00:00 GMT`

2017-01-03 12:48 UTC, ms7s commented on src/main/java/com/infinario/android/infinariosdk/Infinario.java
> +     * @param timestamp event's timestamp in milliseconds
Same here

2017-01-03 18:06 UTC, petee-d commented on README.md
> +Next two arguments are <code>Map&lt;String, Object&gt; properties</code> and <code>Long timestamp</code>. Properties is a map which uses <code>String</code> keys and the value may be any <code>Object
Yeah, I guess "standard UNIX timestamp in milliseconds" is kind of an oxymoron :D

2017-01-04 08:52 UTC, ms7s approved these changes
:+1:

2017-01-04 08:52 UTC, merged